### ISSUE TITLE
fresh generated template does not compile

### ISSUE THREAD

**Issue by hochgi** [zio/zio-project-seed.g8#60]
Due to incompatible / missing dependencies.
errors encountered:
```
$ sbt
[info] [launcher] getting org.scala-sbt sbt 1.5.5  (this may take some time)...
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.5.5/main_2.12-1.5.5.jar ...
…
java.lang.ExceptionInInitializerError
	at $f083fd8911b72ac8913d$.zioSandbox$lzycompute(build.sbt:56)
	at $f083fd8911b72ac8913d$.zioSandbox(build.sbt:54)
	…
Caused by: java.util.NoSuchElementException: key not found: 2.12
	at scala.collection.immutable.Map$Map3.apply(Map.scala:325)
	at BuildHelper$.<init>(BuildHelper.scala:24)
	at BuildHelper$.<clinit>(BuildHelper.scala)
	... 105 more
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
```
Then I fixed the 2.12 version in the `ci.yaml` file and:
```
sbt:root> compile
[info] Updating 
https://repo1.maven.org/maven2/org/scala-native/javalib_native0.4_2.13/0.4.0/javalib_native0.4_2.13-0.4.0.pom
…
[error] stack trace is suppressed; run last zioSandboxJVM / update for the full output
[error] stack trace is suppressed; run last zioSandboxJS / update for the full output
[error] stack trace is suppressed; run last zioSandboxNative / update for the full output
[error] (zioSandboxJVM / update) sbt.librarymanagement.ResolveException: Error downloading com.github.ghik:silencer-lib_2.13.6:1.7.3
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/com.github.ghik/silencer-lib_2.13.6/1.7.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.6/1.7.3/silencer-lib_2.13.6-1.7.3.pom
[error] (zioSandboxJS / update) sbt.librarymanagement.ResolveException: Error downloading com.github.ghik:silencer-lib_2.13.6:1.7.3
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/com.github.ghik/silencer-lib_2.13.6/1.7.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.6/1.7.3/silencer-lib_2.13.6-1.7.3.pom
[error] (zioSandboxNative / update) sbt.librarymanagement.ResolveException: Error downloading com.github.ghik:silencer-lib_2.13.6:1.7.3
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/com.github.ghik/silencer-lib_2.13.6/1.7.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.6/1.7.3/silencer-lib_2.13.6-1.7.3.pom
[error] Total time: 4 s, completed 19 Jul 2021, 13:25:26
sbt:root> last zioSandboxJVM / update
[debug] not up to date. inChanged = true, force = false
[debug] Updating zioSandboxJVM...
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.ghik:silencer-lib_2.13.6:1.7.3
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/com.github.ghik/silencer-lib_2.13.6/1.7.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.6/1.7.3/silencer-lib_2.13.6-1.7.3.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (zioSandboxJVM / update) sbt.librarymanagement.ResolveException: Error downloading com.github.ghik:silencer-lib_2.13.6:1.7.3
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/com.github.ghik/silencer-lib_2.13.6/1.7.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.6/1.7.3/silencer-lib_2.13.6-1.7.3.pom
```
So I updated the silencer plugin version and:
```
sbt:root> +compile
[info] Setting Scala version to 2.11.12 on 4 projects.
…
error] stack trace is suppressed; run last zioSandboxJVM / update for the full output
[error] stack trace is suppressed; run last zioSandboxJS / update for the full output
[error] stack trace is suppressed; run last zioSandboxNative / update for the full output
[error] (zioSandboxJVM / update) sbt.librarymanagement.ResolveException: Error downloading org.typelevel:kind-projector_2.12.14:0.11.3
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/org.typelevel/kind-projector_2.12.14/0.11.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/typelevel/kind-projector_2.12.14/0.11.3/kind-projector_2.12.14-0.11.3.pom
…
```
Then I updated the kind-projector plugin:
```
sbt:root> +compile
[info] Setting Scala version to 2.11.12 on 4 projects.
…
[error] stack trace is suppressed; run last zioSandboxJVM / update for the full output
[error] stack trace is suppressed; run last zioSandboxJS / update for the full output
[error] stack trace is suppressed; run last zioSandboxNative / update for the full output
[error] (zioSandboxJVM / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.14:4.4.10
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.14/4.4.10/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.14/4.4.10/semanticdb-scalac_2.12.14-4.4.10.pom
[error] (zioSandboxJS / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.14:4.4.10
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.14/4.4.10/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.14/4.4.10/semanticdb-scalac_2.12.14-4.4.10.pom
[error] (zioSandboxNative / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.14:4.4.10
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.14/4.4.10/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.14/4.4.10/semanticdb-scalac_2.12.14-4.4.10.pom
[error] Total time: 1 s, completed 19 Jul 2021, 13:31:40
```
And the `semanticdb-scalac` version seems to be derived from scalafix plugin, so I updated that as well:
```
sbt:root> +compile
[info] Setting Scala version to 2.11.12 on 4 projects.
…
[error] stack trace is suppressed; run last zioSandboxJVM / update for the full output
[error] (zioSandboxJVM / update) sbt.librarymanagement.ResolveException: Error downloading dev.zio:zio_3:1.0.7
[error]   Not found
[error]   Not found
[error]   not found: /home/hochgi/.ivy2/local/dev.zio/zio_3/1.0.7/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/dev/zio/zio_3/1.0.7/zio_3-1.0.7.pom
[error] Total time: 0 s, completed 19 Jul 2021, 13:35:14
```
But zio 1.0.7 isn't published against scala, 3.0.0 but against an older RC version, so I updated zio version as well:
```
sbt:root> ;reload;+compile
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.11)
…
[success] Total time: 14 s, completed 19 Jul 2021, 13:37:52
[info] Reapplying settings...
[info] set current project to root (in build file:/home/hochgi/dev/zio-sandbox/)
sbt:root> 
```
and finally build is working properly.
Will open a PR with these changes.

**Comment by hochgi** [comment]
opened a PR #61

**Comment by hochgi** [comment]
PR merged
